### ISSUE TITLE
update license version

### ISSUE THREAD

**Issue by apotheon** [dupliqr/dupliqr.github.io#2]
I see this project uses the Copyfree Open Innovation License.  You may want to
update the license to the 0.6 version.  The 0.6 version has been improved for
legal clarity, and has been reviewed by an attorney.

* [license information](https://coil.apotheon.org/)
* [COIL-0.6 license text](https://coil.apotheon.org/plaintext/00.6.txt)

**Comment by kipbits** [comment]
Thanks, 0.6 it is more readable. However, it's worth noting one of libraries is licensed under Apache 2.0, and is probably why i did not write a more prominent license file for the whole repo to begin with. I need to refamiliarize myself with the Apache 2.0 license, and determine what the implications are. I'll make the necessary change myself. Thanks for the interest in my project!

**Comment by apotheon** [comment]
If you want to discuss license matters, I'm willing to help out.

Note that, for what follows, you should not regard it as legal advice.  I'm not a lawyer -- just someone who reads licenses a lot.

The short version is that using Apache License version 2.0 requires two big things, other than the obvious patent clause, that are likely to be of not for compliance:

* If you modify an AL2-licensed file, you have to make a note about your modification.
* If the original AL2-licensed code came with a NOTICE file, you have to keep that file with any code you borrow, as long as the contents of the file are relevant.

Any files covered by AL2 shouldn't affect the terms of the COIL applied to the whole of the project.

If you're specifically interested in the patent part, again, I'm happy to discuss further.  You could also get into the `##copyfree` channel on the Libera Chat IRC network, where I'm not the only person who could discuss the matter.
